### ISSUE TITLE
authentification

### ISSUE THREAD

**Issue by wapiflapi** [BestPig/bush#8]
We need authentification if this is to be used seriously.
The easiest option is probably to have simple API tokens. A simple list of valid tokens in the configuration file of the server. Can be revoked/changed/whatever by hand. This is easy to configure.
Make sure bush only works over https when checking for tokens!
#### Update:

We will use HTTP Basic-Auth for authentication.
- [x] #45 implements client side
- [x] server side (nothing to do because we delegate this to the webserver)
- [x] update documentation

**Comment by wapiflapi** [comment]
Simply having the client send the token in the `Authorization` HTTP Header should be sufficient for the above proposal. Is this OK with everyone?

What about storage of the tokens on the server side? Can we afford to store them in clear-text or should we offer the option to encrypt them for this not to be considered broken?

**Comment by BestPig** [comment]
What is the point of encrypting them ?
Token are not readable by clients, and the server must be able to decrypt them, so in case of leaking the server "data", they will be readable in all cases.

**Comment by BestPig** [comment]
We can just hash them ;)

**Comment by wapiflapi** [comment]
hashes for the win. Not sure why I didn't think of that. I will implement this soon on the client side.

(Server could have asked for a password when starting or something. but... definitely hashes! problem solved.)

**Comment by wapiflapi** [comment]
This is now WIP. We will use HTTP Basic-Auth for the authentication.

**Comment by wapiflapi** [comment]
#45 and #18 solve the issues on the server and documentation side. redy to close once those are merged.
